# Generated by Django 6.0.7 on 2026-08-16 14:44
#
# CR-004 Listing-grain soft delete (IR-002 / DR-008 delete-on-delist). Both new
# columns are nullable/blank, so every existing row lands active and the
# coherence CHECK holds without a data migration.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_enable_heartbeat_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="delist_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("absent_from_sweep", "Absent from a complete source sweep"),
                    ("absent_stale", "Absent for longer than the source freshness window"),
                    ("source_ended", "Source reported the listing ended"),
                    ("manual", "Manually delisted"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="delisted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                condition=models.Q(("delisted_at__isnull", True)),
                fields=["source_site", "source_listing_key"],
                name="listing_active_by_site_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("delist_reason", ""), ("delisted_at__isnull", True)),
                    models.Q(
                        ("delisted_at__isnull", False),
                        models.Q(("delist_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="listing_delist_reason_coherent",
            ),
        ),
    ]
