# Generated by Django 6.0.7 on 2026-08-16 14:57, then reordered by hand.
#
# ADR-0020 fast/slow-lane scheduling-state split. The three mutable cadence
# columns move off source_config into one row per (source_config, lane), so a
# repair-crawl failure can no longer reset the heartbeat lane's earned interval
# or impose its back-off window (and the reverse).
#
# Operation order is load-bearing in BOTH directions, which is why the generated
# ordering (removals first) was flipped: forward, the lane rows are backfilled
# while the old columns still exist; backward, RemoveField's reverse re-adds the
# columns before the RunPython reverse repopulates them. The AlterField ahead of
# the removal exists only to give current_interval_s a default in migration
# state — without one, the reverse ADD COLUMN of a NOT NULL column against a
# non-empty source_config table fails.
import django.db.models.deletion
from django.db import migrations, models


def split_lane_state(apps, schema_editor):
    """Seed both lane rows per source from the shared columns.

    Interval seeding follows the cadence each lane's JOB actually ran at before
    the split: for a heartbeat source that is cadence_baseline_s for the CR-006
    repair crawl and the shared current_interval_s for the heartbeat probe; for
    a single-lane source the shared value is the full lane's and the (inert)
    heartbeat row starts at baseline. Any pending back-off window is copied to
    BOTH lanes: we cannot tell which lane earned it, and holding a source back
    too long is recoverable while hammering a source that just 429'd is not.
    """
    SourceConfig = apps.get_model("catalog", "SourceConfig")
    SourceLaneState = apps.get_model("catalog", "SourceLaneState")
    rows = []
    for config in SourceConfig.objects.all():
        hb = config.heartbeat_enabled
        rows.append(
            SourceLaneState(
                source_config=config,
                lane="full",
                current_interval_s=(config.cadence_baseline_s if hb else config.current_interval_s),
                clean_polls=0 if hb else config.clean_polls,
                backoff_until=config.backoff_until,
            )
        )
        rows.append(
            SourceLaneState(
                source_config=config,
                lane="heartbeat",
                current_interval_s=(config.current_interval_s if hb else config.cadence_baseline_s),
                clean_polls=config.clean_polls if hb else 0,
                backoff_until=config.backoff_until,
            )
        )
    SourceLaneState.objects.bulk_create(rows)


def merge_lane_state(apps, schema_editor):
    """Best-effort reverse: collapse two lanes back into the shared columns.

    Lossy by construction — the lane that did not drive the source's cadence has
    its interval and clean-poll count discarded. The surviving cadence comes from
    the heartbeat lane for a heartbeat source and the full lane otherwise, while
    the back-off window is the later of the two so no live window is dropped.
    """
    SourceConfig = apps.get_model("catalog", "SourceConfig")
    SourceLaneState = apps.get_model("catalog", "SourceLaneState")
    for config in SourceConfig.objects.all():
        states = {s.lane: s for s in SourceLaneState.objects.filter(source_config=config)}
        primary = states.get("heartbeat" if config.heartbeat_enabled else "full") or next(
            iter(states.values()), None
        )
        if primary is None:
            config.current_interval_s = config.cadence_baseline_s
        else:
            config.current_interval_s = primary.current_interval_s
            config.clean_polls = primary.clean_polls
        windows = [s.backoff_until for s in states.values() if s.backoff_until is not None]
        config.backoff_until = max(windows) if windows else None
        config.save(update_fields=["current_interval_s", "clean_polls", "backoff_until"])


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_listing_delist"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceLaneState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lane",
                    models.CharField(
                        choices=[
                            ("full", "Full-pipeline lane"),
                            ("heartbeat", "Availability-heartbeat lane"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_interval_s", models.PositiveIntegerField()),
                ("clean_polls", models.PositiveIntegerField(default=0)),
                ("backoff_until", models.DateTimeField(blank=True, null=True)),
                (
                    "source_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lane_states",
                        to="catalog.sourceconfig",
                    ),
                ),
            ],
            options={
                "db_table": "source_lane_state",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_config", "lane"), name="source_lane_state_unique_lane"
                    )
                ],
            },
        ),
        migrations.RunPython(split_lane_state, merge_lane_state),
        migrations.AlterField(
            model_name="sourceconfig",
            name="current_interval_s",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="sourceconfig",
            name="backoff_until",
        ),
        migrations.RemoveField(
            model_name="sourceconfig",
            name="clean_polls",
        ),
        migrations.RemoveField(
            model_name="sourceconfig",
            name="current_interval_s",
        ),
    ]
