# Generated by Django 6.0.7 on 2026-08-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_source_lane_state"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="availabilityheartbeatevent",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="avail_hb_event_expires",
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityheartbeatobservation",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="avail_hb_obs_expires",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="listing_expires",
            ),
        ),
        migrations.AddIndex(
            model_name="offersnapshot",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="offer_snapshot_expires",
            ),
        ),
        migrations.AddIndex(
            model_name="rawpayload",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="raw_payload_expires",
            ),
        ),
        migrations.AddIndex(
            model_name="searchobservation",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="search_obs_expires",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationevent",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="verif_event_expires",
            ),
        ),
    ]
