# Generated by Django 6.0.7 on 2026-08-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_retention_expires_at_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcelanestate",
            name="continuous_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
