# Generated by Django 6.0.8 on 2026-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_lane_continuous_since"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="drivespec",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="drive_spec_expires",
            ),
        ),
        migrations.AddIndex(
            model_name="productalias",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="product_alias_expires",
            ),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="product_model_expires",
            ),
        ),
    ]
