# Generated by Django 6.0.8 on 2026-09-24 21:52

"""MS-2 Slice B (MS2-D-04): typed GPU/RAM/CPU spec satellites.

Additive only: three new tables, 1:1 on product_model like drive_spec, each with
the DR-001 CHECK pair and the partial expires_at sweep index from creation, so no
backfill step is needed (the tables start empty). drive_spec and every existing
row are untouched.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_identity_retention_checks"),
    ]

    operations = [
        migrations.CreateModel(
            name="CpuSpec",
            fields=[
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                            ("availability_heartbeat", "Availability heartbeat (30d)"),
                            ("availability_heartbeat_event", "Heartbeat event (365d)"),
                            ("listing_derived_alias", "Listing-derived alias (indefinite)"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cpu_spec",
                        serialize=False,
                        to="catalog.productmodel",
                    ),
                ),
                ("socket", models.CharField(blank=True, default="", max_length=32)),
                ("cores", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tdp_w", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "cpu_spec",
                "indexes": [
                    models.Index(
                        condition=models.Q(("expires_at__isnull", False)),
                        fields=["expires_at"],
                        name="cpu_spec_expires",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("retention_class", ""), _negated=True),
                        name="cpu_spec_retention_class_set",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("expires_at__isnull", True),
                                (
                                    "retention_class__in",
                                    [
                                        "merchant_fact",
                                        "amazon_identifier",
                                        "tavily_extract",
                                        "manufacturer_reference",
                                        "listing_derived_alias",
                                    ],
                                ),
                            ),
                            models.Q(
                                ("expires_at__isnull", False),
                                (
                                    "retention_class__in",
                                    [
                                        "ebay_listing_observation",
                                        "amazon_ephemeral",
                                        "transient_discovery",
                                        "availability_heartbeat",
                                        "availability_heartbeat_event",
                                    ],
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="cpu_spec_retention_ttl_coherent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GpuSpec",
            fields=[
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                            ("availability_heartbeat", "Availability heartbeat (30d)"),
                            ("availability_heartbeat_event", "Heartbeat event (365d)"),
                            ("listing_derived_alias", "Listing-derived alias (indefinite)"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="gpu_spec",
                        serialize=False,
                        to="catalog.productmodel",
                    ),
                ),
                (
                    "chip_vendor",
                    models.CharField(
                        choices=[
                            ("nvidia", "NVIDIA"),
                            ("amd", "AMD"),
                            ("intel", "Intel"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("vram_gb", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "interface",
                    models.CharField(
                        choices=[
                            ("pcie", "PCIe"),
                            ("sxm", "SXM"),
                            ("oam", "OAM"),
                            ("mxm", "MXM"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "cooling",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("passive", "Passive"),
                            ("liquid", "Liquid"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("tdp_w", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "gpu_spec",
                "indexes": [
                    models.Index(
                        condition=models.Q(("expires_at__isnull", False)),
                        fields=["expires_at"],
                        name="gpu_spec_expires",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("retention_class", ""), _negated=True),
                        name="gpu_spec_retention_class_set",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("expires_at__isnull", True),
                                (
                                    "retention_class__in",
                                    [
                                        "merchant_fact",
                                        "amazon_identifier",
                                        "tavily_extract",
                                        "manufacturer_reference",
                                        "listing_derived_alias",
                                    ],
                                ),
                            ),
                            models.Q(
                                ("expires_at__isnull", False),
                                (
                                    "retention_class__in",
                                    [
                                        "ebay_listing_observation",
                                        "amazon_ephemeral",
                                        "transient_discovery",
                                        "availability_heartbeat",
                                        "availability_heartbeat_event",
                                    ],
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="gpu_spec_retention_ttl_coherent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RamSpec",
            fields=[
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                            ("availability_heartbeat", "Availability heartbeat (30d)"),
                            ("availability_heartbeat_event", "Heartbeat event (365d)"),
                            ("listing_derived_alias", "Listing-derived alias (indefinite)"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ram_spec",
                        serialize=False,
                        to="catalog.productmodel",
                    ),
                ),
                (
                    "generation",
                    models.CharField(
                        choices=[
                            ("ddr3", "DDR3"),
                            ("ddr4", "DDR4"),
                            ("ddr5", "DDR5"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("udimm", "UDIMM"),
                            ("rdimm", "RDIMM"),
                            ("lrdimm", "LRDIMM"),
                            ("sodimm", "SO-DIMM"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("ecc", models.BooleanField(blank=True, null=True)),
                ("module_capacity_gb", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("modules_per_kit", models.PositiveSmallIntegerField(default=1)),
                ("speed_mts", models.PositiveIntegerField(blank=True, null=True)),
                ("ranks", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "ram_spec",
                "indexes": [
                    models.Index(
                        condition=models.Q(("expires_at__isnull", False)),
                        fields=["expires_at"],
                        name="ram_spec_expires",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("retention_class", ""), _negated=True),
                        name="ram_spec_retention_class_set",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("expires_at__isnull", True),
                                (
                                    "retention_class__in",
                                    [
                                        "merchant_fact",
                                        "amazon_identifier",
                                        "tavily_extract",
                                        "manufacturer_reference",
                                        "listing_derived_alias",
                                    ],
                                ),
                            ),
                            models.Q(
                                ("expires_at__isnull", False),
                                (
                                    "retention_class__in",
                                    [
                                        "ebay_listing_observation",
                                        "amazon_ephemeral",
                                        "transient_discovery",
                                        "availability_heartbeat",
                                        "availability_heartbeat_event",
                                    ],
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="ram_spec_retention_ttl_coherent",
                    ),
                ],
            },
        ),
    ]
