# Generated by Django 6.0.8 on 2026-09-24 22:08

"""MS-2 Slice C1 (MS2-D-07, -09, -20, -29): watches, requirement satellites, and
the watch_evaluation verdict table.

Additive only: six new tables, no change to any existing table or row, so it
upgrades a DB holding deployed drive data without loss. watch_evaluation carries
the DR-001 CHECK pair and the partial expires_at sweep index from creation, and
all tables start empty, so no backfill step is needed. The reverse drops the six
tables and nothing else.
"""

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.lookups
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_seed_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("enabled", models.BooleanField(default=True)),
                ("requirement_version", models.PositiveIntegerField(default=1)),
                (
                    "max_unit_price_usd",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "allowed_conditions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("new", "New"),
                                ("recertified", "Recertified"),
                                ("refurbished", "Refurbished"),
                                ("used", "Used"),
                                ("open_box", "Open box"),
                                ("for_parts", "For parts / not working"),
                                ("unknown", "Unknown"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                ("require_in_stock", models.BooleanField(default=False)),
                ("allow_international", models.BooleanField(default=True)),
                (
                    "target_unit_price_usd",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="watches",
                        to="catalog.category",
                    ),
                ),
                (
                    "target_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="watches",
                        to="catalog.productfamily",
                    ),
                ),
                (
                    "target_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="watches",
                        to="catalog.productmodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "watches",
                "db_table": "watch",
            },
        ),
        migrations.CreateModel(
            name="CpuRequirement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cpu_requirement",
                        serialize=False,
                        to="catalog.watch",
                    ),
                ),
                (
                    "sockets",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32), blank=True, default=list
                    ),
                ),
                ("min_cores", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_tdp_w", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "cpu_requirement",
            },
        ),
        migrations.CreateModel(
            name="DriveRequirement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="drive_requirement",
                        serialize=False,
                        to="catalog.watch",
                    ),
                ),
                (
                    "min_capacity_tb",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
                ),
                (
                    "media_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("hdd", "HDD"), ("ssd", "SSD"), ("unknown", "Unknown")],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "interfaces",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), blank=True, default=list
                    ),
                ),
                (
                    "form_factors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), blank=True, default=list
                    ),
                ),
                (
                    "recording_techs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("cmr", "CMR"),
                                ("smr_dm", "SMR (device-managed)"),
                                ("smr_hm", "SMR (host-managed)"),
                                ("smr_unknown", "SMR (type unknown)"),
                                ("unknown", "Unknown"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
            ],
            options={
                "db_table": "drive_requirement",
            },
        ),
        migrations.CreateModel(
            name="GpuRequirement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="gpu_requirement",
                        serialize=False,
                        to="catalog.watch",
                    ),
                ),
                ("min_vram_gb", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "chip_vendors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("nvidia", "NVIDIA"),
                                ("amd", "AMD"),
                                ("intel", "Intel"),
                                ("other", "Other"),
                                ("unknown", "Unknown"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "interfaces",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("pcie", "PCIe"),
                                ("sxm", "SXM"),
                                ("oam", "OAM"),
                                ("mxm", "MXM"),
                                ("other", "Other"),
                                ("unknown", "Unknown"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "coolings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("active", "Active"),
                                ("passive", "Passive"),
                                ("liquid", "Liquid"),
                                ("unknown", "Unknown"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                ("max_tdp_w", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "gpu_requirement",
            },
        ),
        migrations.CreateModel(
            name="RamRequirement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ram_requirement",
                        serialize=False,
                        to="catalog.watch",
                    ),
                ),
                (
                    "generations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("ddr3", "DDR3"),
                                ("ddr4", "DDR4"),
                                ("ddr5", "DDR5"),
                                ("other", "Other"),
                                ("unknown", "Unknown"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "module_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("udimm", "UDIMM"),
                                ("rdimm", "RDIMM"),
                                ("lrdimm", "LRDIMM"),
                                ("sodimm", "SO-DIMM"),
                                ("other", "Other"),
                                ("unknown", "Unknown"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                ("require_ecc", models.BooleanField(blank=True, null=True)),
                ("min_total_capacity_gb", models.PositiveIntegerField(blank=True, null=True)),
                ("min_speed_mts", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "ram_requirement",
            },
        ),
        migrations.CreateModel(
            name="WatchEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                            ("availability_heartbeat", "Availability heartbeat (30d)"),
                            ("availability_heartbeat_event", "Heartbeat event (365d)"),
                            ("listing_derived_alias", "Listing-derived alias (indefinite)"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("match", "Match"),
                            ("no_match", "No match"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reasons", models.JSONField(default=list)),
                ("requirement_version", models.PositiveIntegerField()),
                ("evaluator_version", models.CharField(max_length=20)),
                ("snapshot_observed_at", models.DateTimeField(blank=True, null=True)),
                ("catalog_fingerprint", models.CharField(max_length=64)),
                ("evaluated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_evaluations",
                        to="catalog.listing",
                    ),
                ),
                (
                    "resolution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watch_evaluations",
                        to="catalog.listingresolution",
                    ),
                ),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="catalog.watch",
                    ),
                ),
            ],
            options={
                "db_table": "watch_evaluation",
            },
        ),
        migrations.AddConstraint(
            model_name="watch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_family__isnull", True), ("target_model__isnull", True), _connector="OR"
                ),
                name="watch_at_most_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="watchevaluation",
            index=models.Index(fields=["watch", "verdict"], name="watch_eval_watch_verdict"),
        ),
        migrations.AddIndex(
            model_name="watchevaluation",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="watch_evaluation_expires",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchevaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(("retention_class", ""), _negated=True),
                name="watch_evaluation_retention_class_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchevaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        (
                            "retention_class__in",
                            [
                                "merchant_fact",
                                "amazon_identifier",
                                "tavily_extract",
                                "manufacturer_reference",
                                "listing_derived_alias",
                            ],
                        ),
                    ),
                    models.Q(
                        ("expires_at__isnull", False),
                        (
                            "retention_class__in",
                            [
                                "ebay_listing_observation",
                                "amazon_ephemeral",
                                "transient_discovery",
                                "availability_heartbeat",
                                "availability_heartbeat_event",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="watch_evaluation_retention_ttl_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchevaluation",
            constraint=models.UniqueConstraint(
                fields=("watch", "listing"), name="watch_evaluation_one_per_listing"
            ),
        ),
        migrations.AddConstraint(
            model_name="watchevaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(("verdict__in", ["match", "no_match", "unknown"])),
                name="watch_evaluation_verdict_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchevaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    django.db.models.lookups.Exact(
                        models.Func(
                            models.F("reasons"),
                            function="jsonb_typeof",
                            output_field=models.CharField(),
                        ),
                        "array",
                    ),
                    models.Q(("reasons", []), _negated=True),
                ),
                name="watch_evaluation_reasons_nonempty",
            ),
        ),
    ]
