# Generated by Django 6.0.8 on 2026-09-25 10:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_watch_requirements"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider_kind",
                    models.CharField(
                        choices=[("local", "Local collector"), ("apify", "Self-owned Apify Actor")],
                        default="apify",
                        max_length=20,
                    ),
                ),
                ("external_run_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "import_idempotency_key",
                    models.CharField(blank=True, max_length=120, null=True, unique=True),
                ),
                ("actor_ref", models.CharField(blank=True, default="", max_length=200)),
                ("build_id", models.CharField(blank=True, max_length=100, null=True)),
                ("build_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contract_schema_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("query_scope", models.JSONField(blank=True, default=dict)),
                ("scope_key", models.CharField(max_length=100)),
                ("memory_mb", models.PositiveIntegerField()),
                ("timeout_s", models.PositiveIntegerField()),
                ("max_items", models.PositiveIntegerField()),
                ("max_pages", models.PositiveIntegerField()),
                (
                    "admission_class",
                    models.CharField(
                        choices=[
                            ("watch_refresh", "Watch refresh"),
                            ("discovery", "Discovery"),
                            ("operator", "Operator"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "run_kind",
                    models.CharField(
                        choices=[
                            ("full", "Full pipeline"),
                            ("heartbeat", "Availability heartbeat"),
                            ("reference", "Reference-catalog ingest"),
                            ("probe", "Recovery probe"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("admitted_at", models.DateTimeField()),
                ("remote_status", models.CharField(blank=True, max_length=20, null=True)),
                ("remote_terminal_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completeness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("complete", "Complete"),
                            ("truncated", "Truncated"),
                            ("partial_failure", "Partial failure"),
                            ("failed", "Failed"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("completeness_reason", models.TextField(blank=True, default="")),
                (
                    "truncation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("item_limit", "Item limit"),
                            ("page_limit", "Page limit"),
                            ("request_limit", "Request limit"),
                            ("time_limit", "Time limit"),
                            ("resource_limit", "Resource (byte/transfer) limit"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("run_output", models.JSONField(blank=True, null=True)),
                (
                    "usage_total_usd",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
                ),
                ("usage_read_at", models.DateTimeField(blank=True, null=True)),
                ("dataset_id", models.CharField(blank=True, max_length=100, null=True)),
                ("kv_store_id", models.CharField(blank=True, max_length=100, null=True)),
                ("dataset_item_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "import_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("observations_committed", "Observations committed"),
                            ("absence_applied", "Absence applied"),
                            ("resolved", "Resolved"),
                            ("evaluated", "Evaluated"),
                            ("finalized", "Finalized"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "import_listing_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(), blank=True, default=list
                    ),
                ),
                ("stage_detail", models.JSONField(blank=True, default=dict)),
                ("import_attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("dataset_read_count", models.PositiveIntegerField(default=0)),
                ("kv_read_count", models.PositiveIntegerField(default=0)),
                ("run_poll_count", models.PositiveIntegerField(default=0)),
                ("correction_read_count", models.PositiveIntegerField(default=0)),
                ("final_charge_op_at", models.DateTimeField(blank=True, null=True)),
                (
                    "storage_state",
                    models.CharField(
                        choices=[
                            ("retained", "Retained"),
                            ("deleted", "Deleted"),
                            ("delete_failed", "Delete failed"),
                        ],
                        default="retained",
                        max_length=20,
                    ),
                ),
                ("storage_cleanup_due_at", models.DateTimeField()),
                ("storage_cleanup_attempts", models.PositiveIntegerField(default=0)),
                ("storage_deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "provider_run",
            },
        ),
        migrations.CreateModel(
            name="ScopeSweepContinuity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("collection_scope", models.CharField(max_length=100)),
                ("continuous_since", models.DateTimeField(blank=True, null=True)),
                ("last_eligible_sweep_at", models.DateTimeField(blank=True, null=True)),
                ("continuity_broken_at", models.DateTimeField(blank=True, null=True)),
                ("last_complete_sweep_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "scope_sweep_continuity",
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="collection_scope",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="last_absence_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="last_observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourceconfig",
            name="collection_provider",
            field=models.CharField(
                choices=[("local", "Local collector"), ("apify", "Self-owned Apify Actor")],
                default="local",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sourcelanestate",
            name="continuity_broken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcelanestate",
            name="last_complete_sweep_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcelanestate",
            name="last_eligible_sweep_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                condition=models.Q(("delisted_at__isnull", True)),
                fields=["source_site", "collection_scope"],
                name="listing_active_by_site_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("collection_provider__in", ["local", "apify"])),
                name="source_config_collection_provider_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("collection_provider", "local"),
                    models.Q(("fast_lane", False), ("heartbeat_enabled", False)),
                    _connector="OR",
                ),
                name="source_config_remote_provider_local_only_lanes",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcelanestate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lane", "full"),
                    models.Q(
                        ("continuity_broken_at__isnull", True),
                        ("last_complete_sweep_at__isnull", True),
                        ("last_eligible_sweep_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="source_lane_state_scope_watermarks_full_only",
            ),
        ),
        migrations.AddField(
            model_name="providerrun",
            name="scraper_run",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_run",
                to="catalog.scraperrun",
            ),
        ),
        migrations.AddField(
            model_name="providerrun",
            name="source_site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_runs",
                to="catalog.sourcesite",
            ),
        ),
        migrations.AddField(
            model_name="scopesweepcontinuity",
            name="source_site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scope_continuity",
                to="catalog.sourcesite",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerrun",
            constraint=models.UniqueConstraint(
                fields=("provider_kind", "external_run_id"), name="provider_run_unique_external_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("external_run_id__isnull", True), ("import_idempotency_key__isnull", True)
                    ),
                    models.Q(
                        ("external_run_id__isnull", False),
                        ("import_idempotency_key__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="provider_run_idempotency_key_with_run_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_key", ""), _negated=True),
                name="provider_run_scope_key_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_kind__in", ["local", "apify"])),
                name="provider_run_provider_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("run_kind__in", ["full", "probe"])),
                name="provider_run_run_kind_full_or_probe",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("admission_class__in", ["watch_refresh", "discovery"])),
                name="provider_run_admission_class_runtime",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "import_state__in",
                        [
                            "pending",
                            "observations_committed",
                            "absence_applied",
                            "resolved",
                            "evaluated",
                            "finalized",
                            "rejected",
                        ],
                    )
                ),
                name="provider_run_import_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("storage_state__in", ["retained", "deleted", "delete_failed"])),
                name="provider_run_storage_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completeness__in", ["", "complete", "truncated", "partial_failure", "failed"])
                ),
                name="provider_run_completeness_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "truncation_reason__in",
                        [
                            "",
                            "item_limit",
                            "page_limit",
                            "request_limit",
                            "time_limit",
                            "resource_limit",
                        ],
                    )
                ),
                name="provider_run_truncation_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completeness", "truncated"),
                        models.Q(("truncation_reason", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("completeness", "truncated"), _negated=True),
                        ("truncation_reason", ""),
                    ),
                    _connector="OR",
                ),
                name="provider_run_truncation_reason_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopesweepcontinuity",
            constraint=models.UniqueConstraint(
                fields=("source_site", "collection_scope"),
                name="scope_sweep_continuity_unique_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopesweepcontinuity",
            constraint=models.CheckConstraint(
                condition=models.Q(("collection_scope", ""), _negated=True),
                name="scope_sweep_continuity_scope_nonblank",
            ),
        ),
    ]
