# Generated by Django 6.0.8 on 2026-09-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_provider_runs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApifyBudgetCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cycle_start", models.DateTimeField(unique=True)),
                ("cycle_end", models.DateTimeField()),
                (
                    "allocation_usd",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "account_prepaid_credit_usd",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
                ),
                (
                    "account_base_price_usd",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
                ),
                (
                    "account_limit_usd",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
                ),
                (
                    "account_usage_usd",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
                ),
                ("account_observed_at", models.DateTimeField(blank=True, null=True)),
                ("account_data_retention_days", models.PositiveIntegerField(blank=True, null=True)),
                ("account_read_count", models.PositiveIntegerField(default=0)),
                ("opened_at", models.DateTimeField()),
            ],
            options={
                "db_table": "apify_budget_cycle",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cycle_end__gt", models.F("cycle_start"))),
                        name="apify_cycle_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("allocation_usd__isnull", True),
                            ("allocation_usd__gte", 0),
                            _connector="OR",
                        ),
                        name="apify_cycle_allocation_usd_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("account_prepaid_credit_usd__isnull", True),
                            ("account_prepaid_credit_usd__gte", 0),
                            _connector="OR",
                        ),
                        name="apify_cycle_account_prepaid_credit_usd_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("account_base_price_usd__isnull", True),
                            ("account_base_price_usd__gte", 0),
                            _connector="OR",
                        ),
                        name="apify_cycle_account_base_price_usd_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("account_limit_usd__isnull", True),
                            ("account_limit_usd__gte", 0),
                            _connector="OR",
                        ),
                        name="apify_cycle_account_limit_usd_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("account_usage_usd__isnull", True),
                            ("account_usage_usd__gte", 0),
                            _connector="OR",
                        ),
                        name="apify_cycle_account_usage_usd_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ApifyCycleDiscovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("read_count", models.PositiveIntegerField(default=0)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("cycle_start", models.DateTimeField(blank=True, null=True)),
                (
                    "close_reason",
                    models.CharField(
                        blank=True,
                        choices=[("discovered", "Discovered"), ("owner_reset", "Owner reset")],
                        default="",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "apify_cycle_discovery",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("closed_at__isnull", True)),
                        fields=("close_reason",),
                        name="apify_discovery_one_open",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("close_reason__in", ["", "discovered", "owner_reset"])),
                        name="apify_discovery_close_reason_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("close_reason", ""), ("closed_at__isnull", True)),
                            models.Q(
                                ("closed_at__isnull", False),
                                models.Q(("close_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="apify_discovery_closed_with_reason",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("close_reason", "discovered"), _negated=True),
                            ("cycle_start__isnull", False),
                            _connector="OR",
                        ),
                        name="apify_discovery_discovered_has_cycle",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ApifyLedgerAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cycle_start", models.DateTimeField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("origin", "Origin (owner attestation)"),
                            ("handoff", "Handoff (imported record)"),
                            ("continued", "Continued at rollover"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ledger_id", models.CharField(max_length=100)),
                (
                    "carried_consumption_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("attested_by", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField()),
                ("handed_off_at", models.DateTimeField(blank=True, null=True)),
                ("handed_off_to", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "handoff_record_digest",
                    models.CharField(blank=True, max_length=128, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "apify_ledger_authority",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["origin", "handoff", "continued"])),
                        name="apify_authority_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ledger_id", ""), _negated=True),
                        name="apify_authority_ledger_id_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "origin"), _negated=True),
                            models.Q(("attested_by", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="apify_authority_origin_attested",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "handoff"), _negated=True),
                            ("handoff_record_digest__isnull", False),
                            _connector="OR",
                        ),
                        name="apify_authority_handoff_has_digest",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("handed_off_at__isnull", True), ("handed_off_to__isnull", True)
                            ),
                            models.Q(
                                ("handed_off_at__isnull", False),
                                ("handed_off_to__isnull", False),
                                ("handoff_record_digest__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="apify_authority_handoff_binds_destination",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("carried_consumption_usd__isnull", True),
                            ("carried_consumption_usd__gte", 0),
                            _connector="OR",
                        ),
                        name="apify_authority_carried_consumption_usd_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ApifySpendReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "admission_class",
                    models.CharField(
                        choices=[
                            ("watch_refresh", "Watch refresh"),
                            ("discovery", "Discovery"),
                            ("operator", "Operator"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "operator_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("build", "Build"),
                            ("inspect", "Inspect"),
                            ("probe", "Capability probe"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "provider_build_id",
                    models.CharField(blank=True, max_length=100, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("usage_provisional", "Usage provisional"),
                            ("usage_finalized", "Usage finalized"),
                            ("reconciled", "Reconciled"),
                            ("released", "Released"),
                            ("denied", "Denied"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("denial_reason", models.CharField(blank=True, default="", max_length=60)),
                (
                    "estimate_usd",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "execution_bound_usd",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "post_run_liability_usd",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "monitoring_bound_usd",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("component_bounds", models.JSONField(blank=True, default=dict)),
                ("estimator_version", models.CharField(blank=True, default="", max_length=50)),
                ("envelope_max_items", models.PositiveIntegerField(blank=True, null=True)),
                ("envelope_max_record_reads", models.PositiveIntegerField(blank=True, null=True)),
                ("envelope_max_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("envelope_max_calls", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "usage_provisional_usd",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "usage_finalized_usd",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("usage_finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "settlement_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stable_reads", "Stable reads"),
                            ("bound", "Bound"),
                            ("bound_unfinalized", "Bound (unfinalized at deadline)"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "settled_run_usage_usd",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "post_run_cost_usd",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "post_run_cost_mode",
                    models.CharField(
                        blank=True,
                        choices=[("bound", "Bound"), ("counted", "Counted")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "actual_usd",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("reserved_at", models.DateTimeField()),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("last_charge_at", models.DateTimeField(blank=True, null=True)),
                ("correction_monitor_until", models.DateTimeField(blank=True, null=True)),
                ("next_usage_read_at", models.DateTimeField(blank=True, null=True)),
                ("correction_monitor_closed_at", models.DateTimeField(blank=True, null=True)),
                ("monitoring_charge_last_at", models.DateTimeField(blank=True, null=True)),
                ("monitoring_call_pending_since", models.DateTimeField(blank=True, null=True)),
                ("run_poll_count", models.PositiveIntegerField(default=0)),
                ("correction_read_count", models.PositiveIntegerField(default=0)),
                (
                    "provider_run",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spend_reservation",
                        to="catalog.providerrun",
                    ),
                ),
                (
                    "source_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spend_reservations",
                        to="catalog.sourcesite",
                    ),
                ),
            ],
            options={
                "db_table": "apify_spend_reservation",
            },
        ),
        migrations.CreateModel(
            name="ApifyUsageRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("read_at", models.DateTimeField()),
                (
                    "usage_total_usd",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
                ),
                ("usage_usd", models.JSONField(blank=True, default=dict)),
                ("finished_at_reported", models.DateTimeField(blank=True, null=True)),
                ("price_settings_version", models.CharField(blank=True, default="", max_length=50)),
                (
                    "provider_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_reads",
                        to="catalog.providerrun",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_reads",
                        to="catalog.apifyspendreservation",
                    ),
                ),
            ],
            options={
                "db_table": "apify_usage_read",
            },
        ),
        migrations.AddField(
            model_name="apifyspendreservation",
            name="correction_closing_read",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="catalog.apifyusageread",
            ),
        ),
        migrations.CreateModel(
            name="ApifyBudgetLatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tripped_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=60)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("cleared_reason", models.TextField(blank=True, default="")),
                ("estimator_version", models.CharField(blank=True, default="", max_length=50)),
                (
                    "provider_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_latch_trips",
                        to="catalog.providerrun",
                    ),
                ),
            ],
            options={
                "db_table": "apify_budget_latch",
                "indexes": [
                    models.Index(
                        condition=models.Q(("cleared_at__isnull", True)),
                        fields=["tripped_at"],
                        name="apify_latch_open",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="apify_latch_reason_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("cleared_at__isnull", True), ("cleared_reason", "")),
                            models.Q(
                                ("cleared_at__isnull", False),
                                models.Q(("cleared_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="apify_latch_clear_has_reason",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cleared_at__isnull", True),
                            ("cleared_at__gte", models.F("tripped_at")),
                            _connector="OR",
                        ),
                        name="apify_latch_cleared_after_trip",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="apifyusageread",
            index=models.Index(
                fields=["reservation", "read_at"], name="apify_usage_read_resv_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyusageread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("usage_total_usd__isnull", True), ("usage_total_usd__gte", 0), _connector="OR"
                ),
                name="apify_usage_read_usage_total_usd_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="apifyspendreservation",
            index=models.Index(fields=["reserved_at"], name="apify_resv_reserved_at"),
        ),
        migrations.AddIndex(
            model_name="apifyspendreservation",
            index=models.Index(fields=["status"], name="apify_resv_status"),
        ),
        migrations.AddIndex(
            model_name="apifyspendreservation",
            index=models.Index(
                fields=["status", "last_charge_at"], name="apify_resv_status_last_charge"
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("admission_class__in", ["watch_refresh", "discovery", "operator"])
                ),
                name="apify_resv_admission_class_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "reserved",
                            "usage_provisional",
                            "usage_finalized",
                            "reconciled",
                            "released",
                            "denied",
                        ],
                    )
                ),
                name="apify_resv_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("operator_kind__in", ["", "build", "inspect", "probe"])),
                name="apify_resv_operator_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("settlement_basis__in", ["", "stable_reads", "bound", "bound_unfinalized"])
                ),
                name="apify_resv_settlement_basis_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("post_run_cost_mode__in", ["", "bound", "counted"])),
                name="apify_resv_post_run_cost_mode_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("admission_class", "operator"),
                        models.Q(("operator_kind", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("admission_class", "operator"), _negated=True),
                        ("operator_kind", ""),
                    ),
                    _connector="OR",
                ),
                name="apify_resv_operator_kind_iff_operator",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("provider_run__isnull", True),
                    models.Q(
                        ("admission_class__in", ["watch_refresh", "discovery"]),
                        models.Q(("status", "denied"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="apify_resv_run_only_on_admitted_runtime",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("admission_class__in", ["watch_refresh", "discovery"]), _negated=True
                    ),
                    models.Q(
                        ("status__in", ["usage_provisional", "usage_finalized", "reconciled"]),
                        _negated=True,
                    ),
                    ("provider_run__isnull", False),
                    _connector="OR",
                ),
                name="apify_resv_runtime_usage_needs_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("admission_class__in", ["watch_refresh", "discovery"]), _negated=True
                    ),
                    ("source_site__isnull", False),
                    _connector="OR",
                ),
                name="apify_resv_runtime_has_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "denied"), models.Q(("denial_reason", ""), _negated=True)),
                    models.Q(models.Q(("status", "denied"), _negated=True), ("denial_reason", "")),
                    _connector="OR",
                ),
                name="apify_resv_denial_reason_iff_denied",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "denied"),
                    models.Q(
                        ("estimate_usd__isnull", False), ("monitoring_bound_usd__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="apify_resv_admitted_has_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("operator_kind__in", ["inspect", "probe"]), _negated=True),
                    ("monitoring_bound_usd__isnull", True),
                    ("monitoring_bound_usd", 0),
                    _connector="OR",
                ),
                name="apify_resv_envelope_rows_no_monitoring",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("envelope_max_bytes__isnull", False),
                        ("envelope_max_calls__isnull", True),
                        ("envelope_max_items__isnull", False),
                        ("envelope_max_record_reads__isnull", False),
                        ("operator_kind", "inspect"),
                    ),
                    models.Q(
                        ("envelope_max_bytes__isnull", True),
                        ("envelope_max_calls__isnull", False),
                        ("envelope_max_items__isnull", True),
                        ("envelope_max_record_reads__isnull", True),
                        ("operator_kind", "probe"),
                    ),
                    models.Q(
                        models.Q(("operator_kind__in", ["inspect", "probe"]), _negated=True),
                        ("envelope_max_bytes__isnull", True),
                        ("envelope_max_calls__isnull", True),
                        ("envelope_max_items__isnull", True),
                        ("envelope_max_record_reads__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="apify_resv_envelope_limits_by_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("provider_build_id__isnull", True), ("operator_kind", "build"), _connector="OR"
                ),
                name="apify_resv_build_id_only_on_build",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("operator_kind", "build"), ("status", "reconciled"), _negated=True),
                    ("provider_build_id__isnull", False),
                    _connector="OR",
                ),
                name="apify_resv_reconciled_build_has_build_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "reconciled"), _negated=True),
                    models.Q(
                        ("actual_usd__isnull", False),
                        ("last_charge_at__isnull", False),
                        ("reconciled_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="apify_resv_reconciled_has_settlement",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("usage_finalized_at__isnull", True), ("usage_finalized_usd__isnull", True)
                    ),
                    models.Q(
                        ("usage_finalized_at__isnull", False),
                        ("usage_finalized_usd__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="apify_resv_finalized_usage_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("correction_closing_read__isnull", True),
                        ("correction_monitor_closed_at__isnull", True),
                    ),
                    models.Q(
                        ("correction_closing_read__isnull", False),
                        ("correction_monitor_closed_at__isnull", False),
                        ("correction_monitor_until__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="apify_resv_closure_with_closing_read",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estimate_usd__isnull", True), ("estimate_usd__gte", 0), _connector="OR"
                ),
                name="apify_resv_estimate_usd_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_usd__isnull", True), ("actual_usd__gte", 0), _connector="OR"
                ),
                name="apify_resv_actual_usd_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("execution_bound_usd__isnull", True),
                    ("execution_bound_usd__gte", 0),
                    _connector="OR",
                ),
                name="apify_resv_execution_bound_usd_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("post_run_liability_usd__isnull", True),
                    ("post_run_liability_usd__gte", 0),
                    _connector="OR",
                ),
                name="apify_resv_post_run_liability_usd_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("monitoring_bound_usd__isnull", True),
                    ("monitoring_bound_usd__gte", 0),
                    _connector="OR",
                ),
                name="apify_resv_monitoring_bound_usd_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("usage_provisional_usd__isnull", True),
                    ("usage_provisional_usd__gte", 0),
                    _connector="OR",
                ),
                name="apify_resv_usage_provisional_usd_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("usage_finalized_usd__isnull", True),
                    ("usage_finalized_usd__gte", 0),
                    _connector="OR",
                ),
                name="apify_resv_usage_finalized_usd_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("post_run_cost_usd__isnull", True),
                    ("post_run_cost_usd__gte", 0),
                    _connector="OR",
                ),
                name="apify_resv_post_run_cost_usd_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="apifyspendreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("settled_run_usage_usd__isnull", True),
                    ("settled_run_usage_usd__gte", 0),
                    _connector="OR",
                ),
                name="apify_resv_settled_run_usage_usd_non_negative",
            ),
        ),
    ]
