# Generated by Django 6.0.8 on 2026-09-26 18:48
#
# Adds CpuRequirement.require_vendor_unlocked (s8, owner vendor-lock decision).
# Schema-only: every existing CPU watch keeps "no lock constraint" through the
# False default, so no requirement_version bump or data migration is needed;
# the EVALUATOR_VERSION bump that ships with the clause re-evaluates stored
# verdicts instead.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0023_retire_oq31_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpurequirement",
            name="require_vendor_unlocked",
            field=models.BooleanField(default=False),
        ),
    ]
