"""MS-2 Slice D task D4: ApifyImportProvider turns a terminal Actor run into a RawBatch.

Every test drives the provider against an httpx.MockTransport that serves one of
the frozen contract fixtures (tests/fixtures/apify_contract/v1/, generated by the
Actor's own harness), so the dataset rows and the OUTPUT record are exactly what
the real Actor emits for that fault mode. No test touches the network.

The provider is exercised through run_collection where the pipeline's own
behavior is the point (soft-block classification, persisted scope and hint), and
directly where the provider's contract is the point (scope, evidence, paging).

The D10 section at the end drives the durable stage machine
(acquisition.apify.importer) through crashes, read caps, and in-memory retries.
"""

from __future__ import annotations

import asyncio
import copy
import json
from collections.abc import Coroutine, Iterator
from datetime import UTC, datetime, timedelta
from decimal import Decimal
from pathlib import Path
from typing import Any, Final, cast

import httpx
import pytest
from django.db import connection
from django.test import override_settings
from django.utils import timezone

from hw_radar.acquisition import pipeline
from hw_radar.acquisition.apify import importer
from hw_radar.acquisition.apify.client import ApifyClient
from hw_radar.acquisition.apify.contract import (
    DATASET_PAGE_ENVELOPE_BYTES,
    MAX_LISTING_ROW_BYTES,
    ContractViolation,
    page_limit,
)
from hw_radar.acquisition.apify.importer import import_provider_run
from hw_radar.acquisition.apify.provider import (
    OUTPUT_RECORD_KEY,
    ApifyImportError,
    ApifyImportProvider,
    RowRejection,
    import_row,
)
from hw_radar.acquisition.contracts import (
    AdapterRetention,
    NullResolver,
    ParsedListing,
    RawBatch,
    RawItem,
)
from hw_radar.acquisition.pipeline import MEDIAN_BODY_WINDOW, run_collection, run_source
from hw_radar.acquisition.retention_policy import UnknownSourceRetention, source_retention
from hw_radar.acquisition.scheduling.apply import apply_run_outcome
from hw_radar.catalog.models import (
    Category,
    Listing,
    OfferSnapshot,
    ProviderKind,
    ProviderRun,
    RawPayload,
    RetentionClass,
    RunCompleteness,
    RunFailureClass,
    RunKind,
    RunStatus,
    SchedulingLane,
    ScopeSweepContinuity,
    ScraperRun,
    SourceConfig,
    SourceSite,
    SourceTier,
    Watch,
    WatchEvaluation,
)
from hw_radar.catalog.models.ops import TruncationReason
from hw_radar.catalog.models.provider import AdmissionClass, ImportState
from hw_radar.eligibility.requirements import DriveRequirementSpec, save_requirement

# transaction=True: the provider and run_collection write from sync_to_async
# threads. serialized_rollback=True: truncation would otherwise delete the
# migration-seeded SourceSite rows (eBay among them) for every later test.
pytestmark = pytest.mark.django_db(transaction=True, serialized_rollback=True)

FIXTURE_DIR: Final = Path(__file__).resolve().parents[1] / "fixtures" / "apify_contract" / "v1"
SITE: Final = "synthetic"
SCOPE: Final = "synthetic:hdd:catalog"
ACTOR: Final = "hw-radar-synthetic-collector"
DATASET: Final = "ds-d4"
KV_STORE: Final = "kv-d4"
TOKEN: Final = "apify_api_d4_test_token"

C = RunCompleteness
# Classification per fixture (the MS2-D-14 table; tests/unit/test_apify_contract.py
# owns the full reason strings, this file only needs the completeness).
FIXTURE_COMPLETENESS: Final[dict[str, RunCompleteness]] = {
    "complete": C.COMPLETE,
    "complete-empty": C.COMPLETE,
    "ambiguous-empty": C.FAILED,
    "nonempty-unusable": C.FAILED,
    "truncated-by-pages": C.TRUNCATED,
    "truncated-by-items": C.TRUNCATED,
    "truncated-by-bytes": C.TRUNCATED,
    "truncated-by-time": C.TRUNCATED,
    "timed-out": C.TRUNCATED,
    "partial-with-errors": C.PARTIAL_FAILURE,
    "failed-with-items": C.PARTIAL_FAILURE,
    "missing-output": C.FAILED,
    "unknown-schema": C.FAILED,
    "count-mismatch": C.FAILED,
    "complete-with-limit-hit": C.FAILED,
    "status-mismatch": C.FAILED,
    "scope-mismatch": C.FAILED,
}


def _fixture(name: str) -> dict[str, Any]:
    return json.loads((FIXTURE_DIR / f"{name}.json").read_text(encoding="utf-8"))


def _run[T](coro: Coroutine[Any, Any, T]) -> T:
    return asyncio.run(coro)


class FakeApify:
    """MockTransport handler serving one fixture's dataset and OUTPUT record."""

    def __init__(self, rows: list[object], output: object) -> None:
        self.rows = rows
        self.output = output
        self.dataset_requests: list[tuple[int, int]] = []

    def __call__(self, request: httpx.Request) -> httpx.Response:
        if request.url.path == f"/v2/datasets/{DATASET}/items":
            offset = int(request.url.params["offset"])
            limit = int(request.url.params["limit"])
            self.dataset_requests.append((offset, limit))
            return httpx.Response(
                200,
                json=self.rows[offset : offset + limit],
                headers={"X-Apify-Pagination-Total": str(len(self.rows))},
            )
        if request.url.path == f"/v2/key-value-stores/{KV_STORE}/records/{OUTPUT_RECORD_KEY}":
            if self.output is None:
                return httpx.Response(
                    404, json={"error": {"type": "record-not-found", "message": "nope"}}
                )
            if isinstance(self.output, bytes):
                return httpx.Response(200, content=self.output)
            return httpx.Response(200, json=self.output)
        return httpx.Response(500, json={"error": {"type": "unexpected", "message": "path"}})


@pytest.fixture
def synthetic_site() -> Iterator[SourceSite]:
    # F5a creates this site with a management command, not a migration (MS2-D-42).
    yield SourceSite.objects.create(name="Synthetic", normalized_name=SITE)


def _provider_run(
    site: SourceSite, fixture: dict[str, Any], *, run_kind: RunKind = RunKind.FULL
) -> ProviderRun:
    admitted = fixture["admitted"]["queryScope"]
    now = timezone.now()
    return ProviderRun.objects.create(
        source_site=site,
        external_run_id=f"run-{fixture['fixture']}",
        import_idempotency_key=f"apify:run-{fixture['fixture']}",
        actor_ref=ACTOR,
        contract_schema_version="hw-radar-run/v1",
        query_scope=admitted,
        scope_key=admitted["collectionScope"],
        memory_mb=256,
        timeout_s=120,
        max_items=admitted["maxItems"],
        max_pages=admitted["maxPages"],
        admission_class=AdmissionClass.WATCH_REFRESH,
        run_kind=run_kind,
        admitted_at=now - timedelta(minutes=10),
        remote_status=fixture["remoteStatus"],
        started_at=datetime.fromisoformat(fixture["startedAt"]),
        dataset_id=DATASET,
        kv_store_id=KV_STORE,
        storage_cleanup_due_at=now + timedelta(hours=24),
    )


def _provider(row: ProviderRun, fake: FakeApify, *, actor_name: str = ACTOR) -> ApifyImportProvider:
    client = ApifyClient(TOKEN, transport=httpx.MockTransport(fake))
    return ApifyImportProvider(row, client=client, actor_name=actor_name)


def _fake(fixture: dict[str, Any]) -> FakeApify:
    return FakeApify(list(fixture["datasetItems"]), fixture["output"])


def _import(provider: ApifyImportProvider) -> tuple[ScraperRun, RunStatus]:
    retention = provider.retention
    run, _ = _run(
        run_collection(
            provider,
            NullResolver(),
            retention_class=retention.retention_class,
            expires_policy=retention.expires_policy,
        )
    )
    return run, RunStatus(run.status)


def _evidence_json(run: ScraperRun) -> dict[str, object]:
    return cast(dict[str, object], run.detail_json["provider"])


def _fetch_and_parse(provider: ApifyImportProvider) -> tuple[RawBatch, list[ParsedListing]]:
    batch = _run(provider.fetch())
    return batch, provider.parse(batch)


# ── Imported rows carry scope and category hint (revision 5) ──────────────────


def test_imported_rows_carry_scope_and_category_hint(synthetic_site: SourceSite) -> None:
    fixture = _fixture("complete")
    provider = _provider(_provider_run(synthetic_site, fixture), _fake(fixture))

    run, status = _import(provider)

    assert status is RunStatus.SUCCESS, run.error
    expected_keys = {row["sourceListingKey"] for row in fixture["datasetItems"]}
    listings = Listing.objects.filter(source_site=synthetic_site)
    assert {listing.source_listing_key for listing in listings} == expected_keys
    assert {listing.collection_scope for listing in listings} == {SCOPE}
    snapshots = OfferSnapshot.objects.filter(listing__source_site=synthetic_site)
    assert snapshots.count() == len(expected_keys)
    # observed_at is the run's startedAt (MS2-D-13 step 2), never import time.
    started = datetime.fromisoformat(fixture["startedAt"])
    assert {snapshot.observed_at for snapshot in snapshots} == {started}
    assert {snapshot.attrs_json["category_hint"] for snapshot in snapshots} == {"hdd"}
    assert _evidence_json(run)["provider_kind"] == "apify"


def test_scope_is_never_cleared_by_a_scope_less_observation(synthetic_site: SourceSite) -> None:
    # MS2-D-12: a null never overwrites a set value, so a local adapter that has
    # no scope cannot move an imported listing back to the legacy NULL scope.
    fixture = _fixture("complete")
    _import(_provider(_provider_run(synthetic_site, fixture), _fake(fixture)))
    key = fixture["datasetItems"][0]["sourceListingKey"]

    run, _ = _run(run_source(_LocalAdapter([key], body_bytes=10), NullResolver()))

    assert run.status == RunStatus.SUCCESS, run.error
    assert (
        Listing.objects.get(source_site=synthetic_site, source_listing_key=key).collection_scope
        == SCOPE
    )


# ── Remote rows skip the soft-block classifier (MS2-D-28) ─────────────────────


class _LocalAdapter:
    """Local SourceAdapter on the synthetic site whose items carry a fixed body size."""

    name = "synthetic-local"
    site_key = SITE
    run_kind = RunKind.FULL
    expects_json = True
    last_parse_skipped = 0

    def __init__(self, keys: list[str], *, body_bytes: int) -> None:
        self._keys = keys
        self._body = "x" * body_bytes

    async def fetch(self) -> RawBatch:
        # Fresh timestamp per call: observed_at is half of OfferSnapshot's PK.
        return RawBatch(
            source=self.name,
            fetched_at=datetime.now(UTC),
            items=[RawItem(url="https://synthetic.invalid/page", payload_text=self._body)],
        )

    def parse(self, batch: RawBatch) -> list[ParsedListing]:
        return [
            ParsedListing(
                source_listing_key=key,
                url=f"https://synthetic.invalid/{key}",
                title="Synthetic 8TB",
                price=Decimal(100),
                raw_url="https://synthetic.invalid/page",
            )
            for key in self._keys
        ]


def _seed_full_runs(
    site: SourceSite, *, body_bytes: int, provider_kind: str | None, count: int
) -> None:
    """Successful FULL runs whose per-item body average is body_bytes."""
    base = timezone.now()
    for index in range(count):
        detail: dict[str, object] = {"body_bytes": body_bytes}
        if provider_kind is not None:
            detail["provider"] = {"provider_kind": provider_kind}
        ScraperRun.objects.create(
            source_site=site,
            run_kind=RunKind.FULL,
            status=RunStatus.SUCCESS,
            started_at=base + timedelta(seconds=index),
            records_fetched=1,
            detail_json=detail,
        )


def test_provider_switch_does_not_soft_block_imports_or_local_runs(
    synthetic_site: SourceSite,
) -> None:
    # 1. Local history gives the site a 50 kB per-item median. A dataset row is
    #    small JSON with no body text at all, so the EC-007 20% rule would call
    #    every imported row ANTI_BOT if the import ran _classify_batch. One seed
    #    run predates provider evidence (no "provider" key) and must still count.
    _seed_full_runs(synthetic_site, body_bytes=50_000, provider_kind="local", count=3)
    _seed_full_runs(synthetic_site, body_bytes=50_000, provider_kind=None, count=1)
    fixture = _fixture("complete")
    provider = _provider(_provider_run(synthetic_site, fixture), _fake(fixture))

    run, status = _import(provider)

    assert status is RunStatus.SUCCESS, run.error
    assert run.failure_class in ("", None)

    # 2. After the switch, a window's worth of newer remote runs with a huge
    #    per-item average would dominate the median if they were counted, and
    #    push the next ordinary 50 kB local page under 20% of it.
    _seed_full_runs(
        synthetic_site, body_bytes=10_000_000, provider_kind="apify", count=MEDIAN_BODY_WINDOW
    )

    local, _ = _run(run_source(_LocalAdapter(["local-1"], body_bytes=50_000), NullResolver()))

    assert local.status == RunStatus.SUCCESS, local.error


def test_runs_recorded_before_provider_evidence_still_set_the_soft_block_basis(
    synthetic_site: SourceSite,
) -> None:
    # Deployed history predates detail_json["provider"]; the local-only filter
    # must read an absent key as local, or every existing site would lose its
    # EC-007 basis and stop catching soft-blocked pages.
    _seed_full_runs(synthetic_site, body_bytes=50_000, provider_kind=None, count=3)

    run, _ = _run(run_source(_LocalAdapter(["local-1"], body_bytes=100), NullResolver()))

    assert run.status == RunStatus.FAILED
    assert run.failure_class == RunFailureClass.ANTI_BOT


# ── Row admission: siteKey, scope, and the byte cap ───────────────────────────


def _row(**overrides: object) -> dict[str, object]:
    row: dict[str, object] = copy.deepcopy(_fixture("complete")["datasetItems"][0])
    row.update(overrides)
    return row


def _judge(row: object) -> ParsedListing | RowRejection:
    return import_row(row, site_key=SITE, scope_key=SCOPE, max_item_bytes=MAX_LISTING_ROW_BYTES)


def test_contract_valid_row_imports_with_scope_and_hint() -> None:
    parsed = _judge(_row(mpn="SYN-1"))
    assert isinstance(parsed, ParsedListing)
    assert (parsed.collection_scope, parsed.category_hint) == (SCOPE, "hdd")
    assert parsed.attrs == {"mpn": "SYN-1"}


def test_row_for_another_site_is_rejected() -> None:
    assert _judge(_row(siteKey="another-site")) is RowRejection.SITE_KEY_MISMATCH


def test_row_for_another_scope_is_rejected() -> None:
    assert _judge(_row(collectionScope="synthetic:hdd:other")) is RowRejection.SCOPE_MISMATCH


def test_row_over_the_byte_cap_is_rejected_before_validation() -> None:
    # An otherwise valid row padded past the serialized-row bound: the size
    # check must win, so an oversized row is never even handed to the validator.
    padded = _row(title="T" * 400)
    assert isinstance(_judge(padded), ParsedListing)
    size = len(json.dumps(padded, ensure_ascii=True, separators=(",", ":")))
    capped = import_row(padded, site_key=SITE, scope_key=SCOPE, max_item_bytes=size - 1)
    assert capped is RowRejection.OVER_BYTE_CAP
    assert _judge(_row(padding="p" * MAX_LISTING_ROW_BYTES)) is RowRejection.OVER_BYTE_CAP


@pytest.mark.parametrize("row", [["not", "an", "object"], {"schemaVersion": "hw-radar-listing/v1"}])
def test_contract_invalid_row_is_rejected(row: object) -> None:
    assert _judge(row) is RowRejection.CONTRACT_INVALID


def test_contract_valid_but_unpriced_row_is_rejected_not_raised() -> None:
    # The contract admits price "0"; ParsedListing requires price > 0. Raising
    # here would fail the whole run as PARSER_ROT over one row.
    assert _judge(_row(price="0")) is RowRejection.NOT_INGESTIBLE


def test_rejected_rows_make_the_run_a_partial_failure(synthetic_site: SourceSite) -> None:
    # A dropped row is not usable, so a run that dropped one cannot be complete
    # and cannot delist: the listing behind that row would otherwise be marked
    # absent by the very sweep that saw it.
    fixture = _fixture("complete")
    rows = copy.deepcopy(fixture["datasetItems"])
    rows[0]["siteKey"] = "another-site"
    provider = _provider(_provider_run(synthetic_site, fixture), FakeApify(rows, fixture["output"]))

    batch, parsed = _fetch_and_parse(provider)
    scope = provider.delist_scope(batch, parsed)
    evidence = provider.run_evidence(batch, parsed, scope, run_kind=RunKind.FULL)

    assert len(batch.items) == len(rows)
    assert len(parsed) == len(rows) - 1
    assert evidence.completeness is RunCompleteness.PARTIAL_FAILURE
    assert scope is None


# ── delist_scope, run_evidence, and the stored OUTPUT ─────────────────────────


@pytest.mark.parametrize("name", sorted(FIXTURE_COMPLETENESS))
def test_delist_scope_only_for_complete_runs_including_complete_empty(
    synthetic_site: SourceSite, name: str
) -> None:
    fixture = _fixture(name)
    provider = _provider(_provider_run(synthetic_site, fixture), _fake(fixture))

    batch, parsed = _fetch_and_parse(provider)
    scope = provider.delist_scope(batch, parsed)

    if FIXTURE_COMPLETENESS[name] is RunCompleteness.COMPLETE:
        assert scope is not None
        assert scope.complete is True
        assert scope.scope_key == SCOPE
        assert scope.observed_at == datetime.fromisoformat(fixture["startedAt"])
        assert scope.seen_keys == frozenset(p.source_listing_key for p in parsed)
    else:
        assert scope is None


@pytest.mark.parametrize("name", sorted(FIXTURE_COMPLETENESS))
def test_run_evidence_comes_from_classify_run_and_is_never_stale_eligible(
    synthetic_site: SourceSite, name: str
) -> None:
    fixture = _fixture(name)
    row = _provider_run(synthetic_site, fixture)
    provider = _provider(row, _fake(fixture))

    batch, parsed = _fetch_and_parse(provider)
    evidence = provider.run_evidence(batch, parsed, None, run_kind=RunKind.FULL)

    assert evidence.provider_kind is ProviderKind.APIFY
    assert evidence.stale_absence_eligible is False
    assert evidence.completeness is FIXTURE_COMPLETENESS[name]
    row.refresh_from_db()
    assert row.completeness == evidence.completeness
    assert row.completeness_reason == evidence.completeness_reason
    assert row.dataset_item_count == len(fixture["datasetItems"])


def test_output_is_stored_on_provider_run_and_never_becomes_a_raw_item(
    synthetic_site: SourceSite,
) -> None:
    fixture = _fixture("truncated-by-pages")
    row = _provider_run(synthetic_site, fixture)
    provider = _provider(row, _fake(fixture))

    batch = _run(provider.fetch())

    row.refresh_from_db()
    assert row.run_output == fixture["output"]
    assert row.truncation_reason == TruncationReason.PAGE_LIMIT
    assert len(batch.items) == len(fixture["datasetItems"])
    assert all(item.payload_json != fixture["output"] for item in batch.items)
    assert batch.fetched_at == datetime.fromisoformat(fixture["startedAt"])


@pytest.mark.parametrize("name", ["missing-output", "unknown-schema"])
def test_absent_or_invalid_output_is_not_stored(synthetic_site: SourceSite, name: str) -> None:
    # provider_run is not retention-governed (MS2-D-13), so only a record that
    # validates as hw-radar-run/v1 (counts, scope, errors) may land in it.
    fixture = _fixture(name)
    row = _provider_run(synthetic_site, fixture)

    _run(_provider(row, _fake(fixture)).fetch())

    row.refresh_from_db()
    assert row.run_output is None
    assert row.completeness == RunCompleteness.FAILED


def test_undecodable_output_and_non_object_rows_fail_closed(synthetic_site: SourceSite) -> None:
    # A body that is not JSON must classify as invalid_output, not as a missing
    # record, and a non-object row must survive the RawBatch round trip only to
    # be refused by parse, never to crash it.
    fixture = _fixture("complete")
    rows: list[object] = [*fixture["datasetItems"], ["not", "a", "row"]]
    row = _provider_run(synthetic_site, fixture)
    provider = _provider(row, FakeApify(rows, b"\xff not json"))

    batch, parsed = _fetch_and_parse(provider)

    row.refresh_from_db()
    assert row.run_output is None
    assert row.completeness == RunCompleteness.FAILED
    assert row.completeness_reason.startswith("invalid_output")
    assert len(batch.items) == len(rows)
    assert len(parsed) == len(fixture["datasetItems"])


def test_complete_empty_batch_passes_the_zero_record_guard(synthetic_site: SourceSite) -> None:
    # MS2-D-14 raw batch shape: OUTPUT is not a RawItem, so a proven-empty
    # sweep is an empty batch and run_collection's "items but nothing parsed"
    # PARSER_ROT guard does not fire.
    fixture = _fixture("complete-empty")
    run, status = _import(_provider(_provider_run(synthetic_site, fixture), _fake(fixture)))

    assert status is RunStatus.SUCCESS, run.error
    assert run.records_fetched == 0
    assert _evidence_json(run)["completeness_reason"] == "complete_empty"


# ── Retention comes from the registry (MS2-D-25) ──────────────────────────────


def _admitted_for(site_key: str) -> dict[str, Any]:
    """The complete fixture re-admitted for another site's own scope."""
    fixture = copy.deepcopy(_fixture("complete"))
    fixture["admitted"]["queryScope"].update(
        siteKey=site_key, collectionScope=f"{site_key}:hdd:catalog"
    )
    return fixture


def test_retention_comes_from_source_retention_not_the_default() -> None:
    # eBay is registered with a bounded class and a TTL: a default would have
    # been merchant_fact with no expiry, so equality proves the registry won.
    ebay = SourceSite.objects.get(normalized_name="ebay")
    fixture = _admitted_for("ebay")
    provider = _provider(_provider_run(ebay, fixture), _fake(fixture))

    assert provider.retention == source_retention("ebay")
    assert provider.retention.retention_class == RetentionClass.EBAY_LISTING_OBSERVATION
    assert provider.retention != AdapterRetention(
        retention_class=RetentionClass.MERCHANT_FACT, expires_policy=None
    )


def test_unregistered_site_cannot_build_an_import_provider() -> None:
    site = SourceSite.objects.create(name="Unregistered", normalized_name="d4-unregistered")
    fixture = _admitted_for("d4-unregistered")

    with pytest.raises(UnknownSourceRetention):
        _provider(_provider_run(site, fixture), _fake(fixture))


def test_admission_record_must_match_the_rows_site_and_scope(synthetic_site: SourceSite) -> None:
    # The stored admission is what classify_run compares the OUTPUT echo with;
    # one that names another scope would make scope_mismatch check the wrong
    # thing, so the provider refuses to bind to it.
    fixture = _fixture("complete")
    row = _provider_run(synthetic_site, fixture)
    row.scope_key = "synthetic:hdd:elsewhere"

    with pytest.raises(ContractViolation, match="scope_key"):
        _provider(row, _fake(fixture))
    row.query_scope = {"siteKey": SITE}
    with pytest.raises(ContractViolation, match="QueryScope"):
        _provider(row, _fake(fixture))


def test_fetch_refuses_a_run_that_has_not_terminated(synthetic_site: SourceSite) -> None:
    fixture = _fixture("complete")
    row = _provider_run(synthetic_site, fixture)
    row.remote_status = "RUNNING"
    fake = _fake(fixture)

    with pytest.raises(ApifyImportError, match="not terminal"):
        _run(_provider(row, fake).fetch())
    assert fake.dataset_requests == []


def test_run_cannot_be_judged_before_fetch(synthetic_site: SourceSite) -> None:
    fixture = _fixture("complete")
    provider = _provider(_provider_run(synthetic_site, fixture), _fake(fixture))
    empty = RawBatch(source="apify", fetched_at=datetime.now(UTC))

    with pytest.raises(ApifyImportError, match="fetch"):
        provider.delist_scope(empty, [])


# ── Dataset page size (MS2-D-32, revision 11) ─────────────────────────────────


def _many_rows(count: int) -> list[object]:
    return [_row(sourceListingKey=f"syn-many-{index:04d}") for index in range(count)]


def test_page_limit_is_sent_on_every_dataset_page(synthetic_site: SourceSite) -> None:
    fixture = _fixture("complete")
    fake = FakeApify(_many_rows(70), fixture["output"])
    provider = _provider(_provider_run(synthetic_site, fixture), fake)

    batch = _run(provider.fetch())

    limit = page_limit(1_048_576, MAX_LISTING_ROW_BYTES)
    assert limit == 32
    assert fake.dataset_requests == [(0, limit), (32, limit), (64, limit)]
    assert len(batch.items) == 70


@override_settings(
    HW_RADAR_APIFY_MAX_DATASET_PAGE_BYTES=DATASET_PAGE_ENVELOPE_BYTES + 2 * MAX_LISTING_ROW_BYTES
)
def test_page_limit_follows_the_configured_page_byte_cap(synthetic_site: SourceSite) -> None:
    fixture = _fixture("complete")
    fake = FakeApify(_many_rows(5), fixture["output"])
    provider = _provider(_provider_run(synthetic_site, fixture), fake)

    _run(provider.fetch())

    assert fake.dataset_requests == [(0, 2), (2, 2), (4, 2)]


# ── D10: durable staged import (MS2-D-22, -23, -32, -35) ──────────────────────
#
# Crash injection raises a BaseException subclass from a patched stage
# boundary: it escapes every `except Exception` in the importer and the
# pipeline exactly as a process loss would, so whatever the stage had not yet
# committed is rolled back and the next invocation must resume from the
# recorded import_state.


class Crash(BaseException):
    """Simulated process loss at a stage boundary."""


class _FailOnce:
    """Wrap a callable so its first call raises Crash (optionally after running it)."""

    def __init__(self, real: Any, *, after: bool = False) -> None:
        self.real = real
        self.after = after
        self.calls = 0

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        self.calls += 1
        if self.calls == 1:
            if self.after:
                self.real(*args, **kwargs)
            raise Crash
        return self.real(*args, **kwargs)


def _drive_fixture() -> dict[str, Any]:
    # The complete fixture's rows retargeted at the seeded `drive` category, so
    # the production evaluator has a watch to bind; everything else is the
    # Actor's own output.
    fixture = copy.deepcopy(_fixture("complete"))
    for row in fixture["datasetItems"]:
        row["categoryHint"] = "drive"
    return fixture


def _drive_watch() -> Watch:
    watch = Watch.objects.create(name="d10", category=Category.objects.get(slug="drive"))
    save_requirement(watch, DriveRequirementSpec(max_unit_price_usd=Decimal("1000.00")))
    return watch


def _importer_run(
    row: ProviderRun,
    fake: FakeApify,
    *,
    resolver: Any = None,
    evaluator: Any = None,
) -> ImportState:
    client = ApifyClient(TOKEN, transport=httpx.MockTransport(fake))
    return _run(
        import_provider_run(
            row.pk,
            client=client,
            actor_name=ACTOR,
            resolver=resolver if resolver is not None else NullResolver(),
            evaluator=evaluator,
        )
    )


def _counts(site: SourceSite) -> tuple[int, int, int]:
    return (
        Listing.objects.filter(source_site=site).count(),
        OfferSnapshot.objects.filter(listing__source_site=site).count(),
        RawPayload.objects.filter(endpoint__startswith=f"apify-dataset:{DATASET}/").count(),
    )


def _assert_imported_once(
    site: SourceSite, row: ProviderRun, fixture: dict[str, Any], watch: Watch | None = None
) -> ScraperRun:
    row.refresh_from_db()
    assert row.import_state == ImportState.FINALIZED
    rows = len(fixture["datasetItems"])
    assert _counts(site) == (rows, rows, rows)
    assert ScraperRun.objects.filter(source_site=site).count() == 1
    run = ScraperRun.objects.get(source_site=site)
    assert row.scraper_run_id == run.pk  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType] - django-types has no <fk>_id stubs
    assert run.status == RunStatus.SUCCESS
    assert run.snapshots_appended == rows
    started = datetime.fromisoformat(fixture["startedAt"])
    if watch is not None:
        evaluations = WatchEvaluation.objects.filter(watch=watch)
        assert evaluations.count() == rows
        assert {e.snapshot_observed_at for e in evaluations} == {started}
    return run


@pytest.fixture
def crash_setup(synthetic_site: SourceSite) -> tuple[SourceSite, ProviderRun, dict[str, Any]]:
    fixture = _drive_fixture()
    return synthetic_site, _provider_run(synthetic_site, fixture), fixture


def test_crash_after_observation_commit_resumes_without_duplicates(
    crash_setup: tuple[SourceSite, ProviderRun, dict[str, Any]],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    site, row, fixture = crash_setup
    watch = _drive_watch()
    monkeypatch.setattr(importer, "_stage2", _FailOnce(importer._stage2))  # pyright: ignore[reportPrivateUsage]

    with pytest.raises(Crash):
        _importer_run(row, _fake(fixture))
    row.refresh_from_db()
    assert row.import_state == ImportState.OBSERVATIONS_COMMITTED
    assert row.scraper_run is not None
    first_run_pk = row.scraper_run.pk

    fake = _fake(fixture)
    assert _importer_run(row, fake) is ImportState.FINALIZED

    run = _assert_imported_once(site, row, fixture, watch)
    assert run.pk == first_run_pk
    # Resumption past stage 1 never reads the dataset again.
    assert fake.dataset_requests == []
    assert row.dataset_read_count == 1


def test_crash_during_resolution_resumes_and_evaluates(
    crash_setup: tuple[SourceSite, ProviderRun, dict[str, Any]],
) -> None:
    site, row, fixture = crash_setup
    watch = _drive_watch()

    class CrashingResolver:
        def __init__(self) -> None:
            self.calls = 0

        def resolve_listing(self, listing_id: int) -> None:
            self.calls += 1
            if self.calls == 2:
                raise Crash

    with pytest.raises(Crash):
        _importer_run(row, _fake(fixture), resolver=CrashingResolver())
    row.refresh_from_db()
    assert row.import_state == ImportState.ABSENCE_APPLIED

    assert _importer_run(row, _fake(fixture)) is ImportState.FINALIZED
    _assert_imported_once(site, row, fixture, watch)


def test_crash_during_evaluation_resumes_and_evaluates(
    crash_setup: tuple[SourceSite, ProviderRun, dict[str, Any]],
) -> None:
    site, row, fixture = crash_setup
    watch = _drive_watch()

    class CrashingEvaluator:
        def evaluate_listing(self, listing_id: int) -> object:
            raise Crash

    with pytest.raises(Crash):
        _importer_run(row, _fake(fixture), evaluator=CrashingEvaluator())
    row.refresh_from_db()
    assert row.import_state == ImportState.RESOLVED

    assert _importer_run(row, _fake(fixture)) is ImportState.FINALIZED
    _assert_imported_once(site, row, fixture, watch)


def test_crash_before_finalization_finalizes_once(
    crash_setup: tuple[SourceSite, ProviderRun, dict[str, Any]],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    site, row, fixture = crash_setup
    watch = _drive_watch()
    config = SourceConfig.objects.create(
        source_site=site,
        tier=SourceTier.T2_SPECIALIST,
        domain="synthetic.invalid",
        cadence_baseline_s=3600,
        cadence_ceiling_s=900,
        collection_provider=ProviderKind.APIFY,
    )
    lane = config.lane_state(SchedulingLane.FULL)
    clean_before = lane.clean_polls
    # The crash lands inside stage 5's transaction, after the lifecycle outcome
    # was applied: the rollback must undo it, or the retry would apply it twice.
    monkeypatch.setattr(importer, "apply_run_outcome", _FailOnce(apply_run_outcome, after=True))

    with pytest.raises(Crash):
        _importer_run(row, _fake(fixture))
    row.refresh_from_db()
    assert row.import_state == ImportState.EVALUATED
    assert ScraperRun.objects.get(source_site=site).status == RunStatus.RUNNING
    lane.refresh_from_db()
    assert lane.clean_polls == clean_before

    assert _importer_run(row, _fake(fixture)) is ImportState.FINALIZED
    # A third invocation is a no-op at the compare-and-set.
    assert _importer_run(row, _fake(fixture)) is ImportState.FINALIZED
    _assert_imported_once(site, row, fixture, watch)
    lane.refresh_from_db()
    assert lane.clean_polls == clean_before + 1


# ── Read caps (MS2-D-32) ──────────────────────────────────────────────────────


def test_stage1_process_loss_rereads_count_against_read_cap(
    crash_setup: tuple[SourceSite, ProviderRun, dict[str, Any]],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    site, row, fixture = crash_setup
    crash = _FailOnce(importer.persist_observations, after=True)
    monkeypatch.setattr(importer, "persist_observations", crash)

    with pytest.raises(Crash):
        _importer_run(row, _fake(fixture))
    row.refresh_from_db()
    assert (row.import_state, row.dataset_read_count, row.kv_read_count) == (
        ImportState.PENDING,
        1,
        1,
    )
    # The crashed stage-1 transaction left nothing behind.
    assert _counts(site) == (0, 0, 0)

    assert _importer_run(row, _fake(fixture)) is ImportState.FINALIZED
    row.refresh_from_db()
    assert row.dataset_read_count == 2
    _assert_imported_once(site, row, fixture)


def test_read_cap_exhausted_rejects_import_and_cleans_up(
    crash_setup: tuple[SourceSite, ProviderRun, dict[str, Any]],
) -> None:
    site, row, fixture = crash_setup
    ProviderRun.objects.filter(pk=row.pk).update(
        dataset_read_count=importer.DEFAULT_MAX_DATASET_READS
    )
    fake = _fake(fixture)

    assert _importer_run(row, fake) is ImportState.REJECTED

    row.refresh_from_db()
    assert row.stage_detail["reject_reason"] == "read_cap_exhausted"
    assert row.dataset_read_count == importer.DEFAULT_MAX_DATASET_READS
    assert fake.dataset_requests == []
    assert _counts(site) == (0, 0, 0)
    run = ScraperRun.objects.get(source_site=site)
    assert run.status == RunStatus.FAILED
    # Rejection leaves storage retained for D11's cleanup selector: import is
    # terminal while storage_state is not `deleted` (MS2-D-23 selector 2).
    assert row.storage_state == "retained"


def test_failed_run_is_rejected_before_anything_is_persisted(synthetic_site: SourceSite) -> None:
    fixture = _fixture("ambiguous-empty")
    row = _provider_run(synthetic_site, fixture)

    assert _importer_run(row, _fake(fixture)) is ImportState.REJECTED

    row.refresh_from_db()
    assert row.stage_detail["reject_reason"] == "failed_run"
    assert _counts(synthetic_site) == (0, 0, 0)
    assert ScraperRun.objects.get(source_site=synthetic_site).status == RunStatus.FAILED
    # The admitted scope's continuity is broken at the run's startedAt.
    continuity = ScopeSweepContinuity.objects.get(
        source_site=synthetic_site, collection_scope=SCOPE
    )
    assert continuity.continuity_broken_at == datetime.fromisoformat(fixture["startedAt"])


# ── In-memory retry (MS2-D-35) ────────────────────────────────────────────────


def _raise_sqlstate(code: str) -> None:
    # A real Postgres abort with the given SQLSTATE, raised inside the
    # transaction under test, so Django wraps it exactly as a real conflict.
    with connection.cursor() as cursor:
        cursor.execute(f"DO $$ BEGIN RAISE EXCEPTION 'injected' USING ERRCODE = '{code}'; END $$")


class _AbortAfter:
    """Run the real stage body, then abort its transaction with `code` `times` times."""

    def __init__(self, real: Any, code: str, *, times: int) -> None:
        self.real = real
        self.code = code
        self.times = times
        self.calls = 0

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        result = self.real(*args, **kwargs)
        self.calls += 1
        if self.calls <= self.times:
            _raise_sqlstate(self.code)
        return result


@pytest.mark.parametrize("code", ["40P01", "40001", "23505"])
@pytest.mark.parametrize("stage", ["persist_observations", "apply_absence"])
def test_forced_retryable_sqlstate_retried_in_memory_without_reread(
    crash_setup: tuple[SourceSite, ProviderRun, dict[str, Any]],
    monkeypatch: pytest.MonkeyPatch,
    code: str,
    stage: str,
) -> None:
    site, row, fixture = crash_setup
    abort = _AbortAfter(getattr(importer, stage), code, times=1)
    monkeypatch.setattr(importer, stage, abort)

    assert _importer_run(row, _fake(fixture)) is ImportState.FINALIZED

    assert abort.calls == 2
    row.refresh_from_db()
    assert row.dataset_read_count == 1
    assert len(row.import_listing_ids) == len(fixture["datasetItems"])
    assert row.stage_detail["snapshots_appended"] == len(fixture["datasetItems"])
    _assert_imported_once(site, row, fixture)


def test_retry_exhaustion_leaves_no_partial_effects_and_next_tick_rereads_counted(
    crash_setup: tuple[SourceSite, ProviderRun, dict[str, Any]],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    site, row, fixture = crash_setup
    abort = _AbortAfter(importer.persist_observations, "40P01", times=4)
    monkeypatch.setattr(importer, "persist_observations", abort)
    before = timezone.now()

    assert _importer_run(row, _fake(fixture)) is ImportState.PENDING

    assert abort.calls == 4
    row.refresh_from_db()
    assert _counts(site) == (0, 0, 0)
    assert row.stage_detail["retry_exhausted"] == 1
    assert row.next_attempt_at is not None and row.next_attempt_at > before
    assert row.dataset_read_count == 1

    assert _importer_run(row, _fake(fixture)) is ImportState.FINALIZED
    row.refresh_from_db()
    assert row.dataset_read_count == 2
    _assert_imported_once(site, row, fixture)


def test_local_persist_retry_exhaustion_rolls_back_like_a_crash(
    synthetic_site: SourceSite, monkeypatch: pytest.MonkeyPatch
) -> None:
    abort = _AbortAfter(pipeline.persist_observations, "40001", times=4)
    monkeypatch.setattr(pipeline, "persist_observations", abort)

    run, _ = _run(run_source(_LocalAdapter(["a", "b"], body_bytes=100), NullResolver()))

    assert run.status == RunStatus.FAILED
    assert abort.calls == 4
    assert Listing.objects.filter(source_site=synthetic_site).count() == 0
    assert OfferSnapshot.objects.filter(listing__source_site=synthetic_site).count() == 0


# ── Reject preconditions and PROBE (MS2-D-22 *Reject*, MS2-D-33) ──────────────


def test_storage_deadline_passed_rejects_before_any_read(
    crash_setup: tuple[SourceSite, ProviderRun, dict[str, Any]],
) -> None:
    site, row, fixture = crash_setup
    ProviderRun.objects.filter(pk=row.pk).update(
        storage_cleanup_due_at=timezone.now() - timedelta(seconds=1)
    )
    fake = _fake(fixture)

    assert _importer_run(row, fake) is ImportState.REJECTED

    row.refresh_from_db()
    assert row.stage_detail["reject_reason"] == "storage_deadline_passed"
    assert (row.dataset_read_count, fake.dataset_requests) == (0, [])
    assert _counts(site) == (0, 0, 0)


def test_content_past_source_ttl_rejects_before_any_read(
    crash_setup: tuple[SourceSite, ProviderRun, dict[str, Any]],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _site, row, fixture = crash_setup
    # A bounded six-hour class: the fixture's startedAt is a day old, so its
    # content is already past the source TTL before the import starts.
    bounded = AdapterRetention(
        retention_class=RetentionClass.EBAY_LISTING_OBSERVATION,
        expires_policy=lambda at: at + timedelta(hours=6),
    )

    def bounded_retention(_key: str) -> AdapterRetention:
        return bounded

    monkeypatch.setattr("hw_radar.acquisition.apify.provider.source_retention", bounded_retention)
    fake = _fake(fixture)

    assert _importer_run(row, fake) is ImportState.REJECTED

    row.refresh_from_db()
    assert row.stage_detail["reject_reason"] == "content_past_ttl"
    assert fake.dataset_requests == []


def test_unregistered_retention_rejects_the_import(synthetic_site: SourceSite) -> None:
    other = SourceSite.objects.create(name="Unregistered", normalized_name="d10-unregistered")
    fixture = _fixture("complete")
    row = _provider_run(synthetic_site, fixture)
    ProviderRun.objects.filter(pk=row.pk).update(source_site=other)

    assert _importer_run(row, _fake(fixture)) is ImportState.REJECTED

    row.refresh_from_db()
    assert row.stage_detail["reject_reason"] == "unknown_retention"


def test_probe_import_finalizes_without_touching_continuity(synthetic_site: SourceSite) -> None:
    fixture = _fixture("complete")
    row = _provider_run(synthetic_site, fixture, run_kind=RunKind.PROBE)

    assert _importer_run(row, _fake(fixture)) is ImportState.FINALIZED

    assert not ScopeSweepContinuity.objects.filter(
        source_site=synthetic_site, continuous_since__isnull=False
    ).exists()
    assert not ScopeSweepContinuity.objects.filter(
        source_site=synthetic_site, continuity_broken_at__isnull=False
    ).exists()
    assert ScraperRun.objects.get(source_site=synthetic_site).run_kind == RunKind.PROBE


def test_resolver_errors_are_counted_and_skip_evaluation(
    crash_setup: tuple[SourceSite, ProviderRun, dict[str, Any]],
) -> None:
    site, row, fixture = crash_setup

    class FailingResolver:
        def resolve_listing(self, listing_id: int) -> None:
            raise RuntimeError("resolver down")

    class RecordingEvaluator:
        def __init__(self) -> None:
            self.calls: list[int] = []

        def evaluate_listing(self, listing_id: int) -> object:
            self.calls.append(listing_id)
            return None

    evaluator = RecordingEvaluator()
    assert (
        _importer_run(row, _fake(fixture), resolver=FailingResolver(), evaluator=evaluator)
        is ImportState.FINALIZED
    )

    run = ScraperRun.objects.get(source_site=site)
    assert run.detail_json["resolver_errors"] == len(fixture["datasetItems"])
    assert evaluator.calls == []
