"""MS2-D-14 Actor contract: drift guards, input validation, and the run classifier.

The fixtures under tests/fixtures/apify_contract/v1/ are generated by the Actor's
own test harness (actors/hw-radar-synthetic-collector/tests/support.py) from its
faultMode, and the Actor's tests fail if they drift, so the classifier is tested
against what the real Actor emits rather than hand-written JSON. This file never
imports the Actor; it reads the committed schema files only.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Any, Final

import httpx
import pytest
from pydantic import BaseModel

from hw_radar.acquisition.apify.contract import (
    CONTRACT_SCHEMA_MODELS,
    AdmittedRun,
    CollectorInput,
    ContractViolation,
    ListingRow,
    QueryScope,
    RunClassification,
    classify_run,
    prepare_run_input,
    usable_rows,
)
from hw_radar.catalog.models import RunCompleteness, StockStatus
from hw_radar.catalog.models.ops import TruncationReason

REPO_ROOT: Final = Path(__file__).resolve().parents[2]
ACTOR_DIR: Final = REPO_ROOT / "actors" / "hw-radar-synthetic-collector"
CONTRACT_DIR: Final = ACTOR_DIR / "contract"
FIXTURE_DIR: Final = REPO_ROOT / "tests" / "fixtures" / "apify_contract" / "v1"

C = RunCompleteness
T = TruncationReason

# The MS2-D-14 mapping table: fixture -> (completeness, reason prefix, truncation reason).
EXPECTED: Final[dict[str, tuple[RunCompleteness, str, TruncationReason | None]]] = {
    "complete": (C.COMPLETE, "complete", None),
    "complete-empty": (C.COMPLETE, "complete_empty", None),
    "ambiguous-empty": (C.FAILED, "ambiguous_empty", None),
    "nonempty-unusable": (C.FAILED, "no_usable_items", None),
    "truncated-by-pages": (C.TRUNCATED, "truncated: pages", T.PAGE_LIMIT),
    "truncated-by-items": (C.TRUNCATED, "truncated: items", T.ITEM_LIMIT),
    "truncated-by-bytes": (C.TRUNCATED, "truncated: bytes", T.RESOURCE_LIMIT),
    "truncated-by-time": (C.TRUNCATED, "truncated: time", T.TIME_LIMIT),
    "timed-out": (C.TRUNCATED, "truncated: time", T.TIME_LIMIT),
    "partial-with-errors": (C.PARTIAL_FAILURE, "errors_reported: injected_fetch_error", None),
    "failed-with-items": (C.PARTIAL_FAILURE, "remote_failed_with_items: FAILED", None),
    "missing-output": (C.FAILED, "missing_output", None),
    "unknown-schema": (C.FAILED, "unknown_schema_version", None),
    "count-mismatch": (C.FAILED, "contradictory_report: count_mismatch", None),
    "complete-with-limit-hit": (C.FAILED, "contradictory_report: complete_with_limit_hit", None),
    "status-mismatch": (C.FAILED, "contradictory_report: status_mismatch", None),
    "scope-mismatch": (C.FAILED, "scope_mismatch", None),
}


def _fixture(name: str) -> dict[str, Any]:
    return json.loads((FIXTURE_DIR / f"{name}.json").read_text(encoding="utf-8"))


def _admitted(fixture: dict[str, Any]) -> AdmittedRun:
    admitted = fixture["admitted"]
    return AdmittedRun(
        query_scope=QueryScope.model_validate(admitted["queryScope"]),
        actor_name=admitted["actorName"],
    )


def _classify(
    fixture: dict[str, Any], *, remote_status: str | None = None, output: object = ...
) -> RunClassification:
    rows: list[object] = list(fixture["datasetItems"])
    return classify_run(
        remote_status or fixture["remoteStatus"],
        fixture["output"] if output is ... else output,
        len(rows),
        len(usable_rows(rows)),
        admitted=_admitted(fixture),
    )


def _with_report(name: str, **changes: object) -> dict[str, Any]:
    """A copy of a fixture's OUTPUT with completeness keys replaced (None deletes)."""
    output = copy.deepcopy(_fixture(name)["output"])
    for key, value in changes.items():
        if value is None:
            output["completeness"].pop(key, None)
        else:
            output["completeness"][key] = value
    return output


# ── Drift guards ──────────────────────────────────────────────────────────────


@pytest.mark.parametrize(("file_name", "model"), CONTRACT_SCHEMA_MODELS.items())
def test_pydantic_models_equal_committed_contract_schemas(
    file_name: str, model: type[BaseModel]
) -> None:
    committed = json.loads((CONTRACT_DIR / file_name).read_text(encoding="utf-8"))

    assert committed == model.model_json_schema(), (
        f"{file_name} and {model.__name__} drifted; a contract change edits both in one PR"
    )


def test_contract_directory_holds_exactly_the_modelled_schemas() -> None:
    assert sorted(path.name for path in CONTRACT_DIR.glob("*.json")) == sorted(
        CONTRACT_SCHEMA_MODELS
    )


def _normalized_property(spec: dict[str, Any]) -> dict[str, Any]:
    """The comparable facets of one input property: type, enum, and bounds."""
    facets: dict[str, Any] = {"type": spec["type"]}
    if "const" in spec:
        facets["enum"] = [spec["const"]]
    for key in (
        "enum",
        "minimum",
        "maximum",
        "minLength",
        "maxLength",
        "minItems",
        "maxItems",
        "pattern",
    ):
        if key in spec:
            facets[key] = spec[key]
    return facets


def test_apify_input_schema_matches_contract_input() -> None:
    contract = json.loads(
        (CONTRACT_DIR / "hw-radar-input-v1.schema.json").read_text(encoding="utf-8")
    )
    apify = json.loads((ACTOR_DIR / ".actor" / "input_schema.json").read_text(encoding="utf-8"))

    assert apify["schemaVersion"] == 1
    assert set(apify["properties"]) == set(contract["properties"])
    assert set(apify["required"]) == set(contract["required"])
    for name, spec in contract["properties"].items():
        assert _normalized_property(apify["properties"][name]) == _normalized_property(spec), name


def test_fault_mode_is_never_part_of_the_common_input() -> None:
    common = set(CollectorInput.model_json_schema()["properties"])

    assert "faultMode" not in common
    assert not {name for name in common if "proxy" in name.lower()}


def test_stock_status_values_mirror_the_catalog() -> None:
    listing = ListingRow.model_json_schema()["properties"]["stockStatus"]

    assert set(listing["enum"]) == set(StockStatus.values)


def test_every_listing_string_is_length_capped() -> None:
    """Per-field maxLength is the MS2-D-26 per-row byte cap; an uncapped string breaks it."""
    uncapped: list[str] = []
    for name, spec in ListingRow.model_json_schema()["properties"].items():
        variants = spec.get("anyOf", [spec])
        for variant in variants:
            if (
                variant.get("type") == "string"
                and not {"maxLength", "const", "enum"} & variant.keys()
            ):
                uncapped.append(name)
    assert uncapped == []


# ── Input validation before any start request ─────────────────────────────────


def _valid_input(**overrides: object) -> dict[str, object]:
    return {**_fixture("complete")["actorInput"], **overrides}


def _start_run(client: httpx.Client, payload: dict[str, object]) -> httpx.Response:
    # The order D5's start path must keep: validate, then build the request.
    body = prepare_run_input(payload)
    return client.post("https://api.apify.com/v2/acts/actor-under-test/runs", json=body)


@pytest.mark.parametrize(
    "overrides",
    [
        {"maxItems": 0},
        {"maxItems": "5"},
        {"maxBytes": 10_000_001},
        {"timeBudgetSecs": True},
        {"schemaVersion": "hw-radar-input/v2"},
        {"fixtureCommit": "main"},
        {"fixturePaths": ["../../../etc/passwd.json"]},
        {"fixturePaths": ["https://example.com/page.json"]},
        {"faultMode": "explode"},
        {"collectionScope": "not-a-scope-key"},
        {"proxyConfiguration": {"useApifyProxy": True}},
    ],
    ids=lambda overrides: next(iter(overrides)),
)
def test_invalid_input_rejected_before_start_request(overrides: dict[str, object]) -> None:
    sent: list[httpx.Request] = []
    transport = httpx.MockTransport(lambda request: sent.append(request) or httpx.Response(201))

    with httpx.Client(transport=transport) as client, pytest.raises(ContractViolation):
        _start_run(client, _valid_input(**overrides))

    assert sent == []


def test_missing_input_field_rejected_before_start_request() -> None:
    payload = _valid_input()
    del payload["faultMode"]

    with pytest.raises(ContractViolation):
        prepare_run_input(payload)


def test_valid_input_is_sent_unchanged() -> None:
    sent: list[httpx.Request] = []
    transport = httpx.MockTransport(lambda request: sent.append(request) or httpx.Response(201))

    with httpx.Client(transport=transport) as client:
        _start_run(client, _valid_input())

    assert [json.loads(request.content) for request in sent] == [_valid_input()]


# ── The classifier over every fixture ─────────────────────────────────────────


def test_every_fixture_has_an_expected_classification() -> None:
    assert sorted(path.stem for path in FIXTURE_DIR.glob("*.json")) == sorted(EXPECTED)


@pytest.mark.parametrize("name", sorted(EXPECTED))
def test_mapping_table_over_every_fixture(name: str) -> None:
    completeness, reason_prefix, truncation = EXPECTED[name]

    result = _classify(_fixture(name))

    assert result.completeness is completeness
    assert result.reason.startswith(reason_prefix), result.reason
    assert result.truncation_reason is truncation


@pytest.mark.parametrize(
    "output",
    [
        None,
        [],
        "OUTPUT",
        {"schemaVersion": "hw-radar-run/v1"},
        _with_report("complete", complete=None),
        _with_report("complete", itemsEmitted=None),
        _with_report("complete", limitsHit=None),
        _with_report("complete", complete="true"),
        _with_report("complete", itemsEmitted=-1),
        {**_fixture("complete")["output"], "schemaVersion": None},
        {**_fixture("complete")["output"], "extra": "field"},
    ],
    ids=lambda value: repr(value)[:40],
)
def test_unknown_or_missing_evidence_is_never_complete(output: object) -> None:
    result = _classify(_fixture("complete"), output=output)

    assert result.completeness is C.FAILED
    assert result.truncation_reason is None


def test_unknown_schema_version_is_failed() -> None:
    result = _classify(_fixture("unknown-schema"))

    assert result == RunClassification(C.FAILED, "unknown_schema_version: 'hw-radar-run/v99'", None)


@pytest.mark.parametrize(
    "changes",
    [
        {"pagesFetched": 0},
        {"itemsDeclared": 1},
        {"itemsDeclared": None},
        {"complete": False},
    ],
    ids=lambda changes: next(iter(changes)),
)
def test_complete_empty_requires_all_zero_counts_and_pages_fetched(
    changes: dict[str, object],
) -> None:
    fixture = _fixture("complete-empty")
    assert _classify(fixture).reason == "complete_empty"

    result = _classify(fixture, output=_with_report("complete-empty", **changes))

    assert result.completeness is C.FAILED


def test_complete_empty_requires_succeeded() -> None:
    result = _classify(_fixture("complete-empty"), remote_status="ABORTED")

    assert result.completeness is C.FAILED


def test_empty_without_evidence_is_failed_ambiguous() -> None:
    fixture = _fixture("ambiguous-empty")
    assert "itemsDeclared" not in fixture["output"]["completeness"]
    assert fixture["datasetItems"] == []

    assert _classify(fixture) == RunClassification(C.FAILED, "ambiguous_empty", None)


def test_nonempty_unusable_is_failed_not_complete_empty() -> None:
    fixture = _fixture("nonempty-unusable")
    assert fixture["datasetItems"]
    assert usable_rows(fixture["datasetItems"]) == []

    assert _classify(fixture) == RunClassification(C.FAILED, "no_usable_items", None)


# ── Truncation reasons (revision 5) ───────────────────────────────────────────


def test_truncation_reason_distinguishes_items_pages_time_bytes() -> None:
    reasons = {
        name: _classify(_fixture(name)).truncation_reason
        for name in (
            "truncated-by-items",
            "truncated-by-pages",
            "truncated-by-time",
            "truncated-by-bytes",
        )
    }

    assert reasons == {
        "truncated-by-items": T.ITEM_LIMIT,
        "truncated-by-pages": T.PAGE_LIMIT,
        "truncated-by-time": T.TIME_LIMIT,
        "truncated-by-bytes": T.RESOURCE_LIMIT,
    }
    assert all(_classify(_fixture(name)).completeness is C.TRUNCATED for name in reasons)


def _limits(**hit: bool) -> dict[str, bool]:
    return {name: hit.get(name, False) for name in ("pages", "requests", "items", "time", "bytes")}


@pytest.mark.parametrize(
    ("hit", "expected", "listed"),
    [
        (
            _limits(pages=True, requests=True, items=True, time=True, bytes=True),
            T.TIME_LIMIT,
            "time, bytes, requests, pages, items",
        ),
        (_limits(bytes=True, requests=True), T.RESOURCE_LIMIT, "bytes, requests"),
        (_limits(requests=True, pages=True), T.REQUEST_LIMIT, "requests, pages"),
        (_limits(pages=True, items=True), T.PAGE_LIMIT, "pages, items"),
    ],
)
def test_truncation_precedence_is_time_bytes_requests_pages_items(
    hit: dict[str, bool], expected: TruncationReason, listed: str
) -> None:
    output = _with_report("truncated-by-items", limitsHit=hit)

    result = _classify(_fixture("truncated-by-items"), output=output)

    assert result == RunClassification(C.TRUNCATED, f"truncated: {listed}", expected)


def test_timed_out_without_an_actor_flag_is_a_time_limit() -> None:
    output = _with_report("truncated-by-pages", limitsHit=_limits(), truncated=True)

    result = _classify(_fixture("truncated-by-pages"), remote_status="TIMED-OUT", output=output)

    assert result == RunClassification(C.TRUNCATED, "truncated: time", T.TIME_LIMIT)


def test_timed_out_run_that_claimed_completion_is_still_truncated() -> None:
    result = _classify(_fixture("complete"), remote_status="TIMED-OUT")

    assert result == RunClassification(C.TRUNCATED, "truncated: time", T.TIME_LIMIT)


# ── Contradiction and scope ───────────────────────────────────────────────────


@pytest.mark.parametrize(
    ("name", "contradiction"),
    [
        ("complete-with-limit-hit", "complete_with_limit_hit"),
        ("count-mismatch", "count_mismatch"),
        ("status-mismatch", "status_mismatch"),
    ],
)
def test_contradictory_report_is_failed(name: str, contradiction: str) -> None:
    result = _classify(_fixture(name))

    assert result == RunClassification(C.FAILED, f"contradictory_report: {contradiction}", None)


@pytest.mark.parametrize(
    ("changes", "contradiction"),
    [
        ({"truncated": True}, "complete_and_truncated"),
        ({"complete": False, "truncated": True}, "truncated_without_limit_hit"),
        ({"pagesFetched": 3}, "pages_fetched_exceed_declared"),
    ],
)
def test_other_self_contradictions_are_failed(
    changes: dict[str, object], contradiction: str
) -> None:
    result = _classify(_fixture("complete"), output=_with_report("complete", **changes))

    assert result.completeness is C.FAILED
    assert contradiction in result.reason


@pytest.mark.parametrize(
    ("changes", "contradiction"),
    [
        # The source declared 3 items; a complete report must have emitted all 3.
        ({"itemsDeclared": 4}, "complete_with_items_declared_mismatch"),
        ({"itemsDeclared": 2}, "complete_with_items_declared_mismatch"),
        # The source declared 2 pages; a complete report must have fetched both.
        ({"pagesFetched": 1}, "complete_with_pages_unfetched"),
        ({"pagesDeclared": 3}, "complete_with_pages_unfetched"),
    ],
)
def test_complete_report_contradicting_declared_counts_is_failed(
    changes: dict[str, object], contradiction: str
) -> None:
    fixture = _fixture("complete")
    assert _classify(fixture) == RunClassification(C.COMPLETE, "complete", None)

    result = _classify(fixture, output=_with_report("complete", **changes))

    assert result == RunClassification(C.FAILED, f"contradictory_report: {contradiction}", None)


def test_incomplete_report_may_fall_short_of_declared_counts() -> None:
    # Truncated and partial runs legitimately fetch fewer pages and items than
    # the source declared; only a completeness claim makes the shortfall a lie.
    fixture = _fixture("truncated-by-pages")
    report = fixture["output"]["completeness"]
    assert report["pagesFetched"] < report["pagesDeclared"]
    assert report["itemsEmitted"] < report["itemsDeclared"]

    assert _classify(fixture).completeness is C.TRUNCATED


def test_scope_mismatch_is_failed() -> None:
    assert _classify(_fixture("scope-mismatch")) == RunClassification(
        C.FAILED, "scope_mismatch", None
    )

    fixture = _fixture("complete")
    other_actor = AdmittedRun(
        query_scope=_admitted(fixture).query_scope, actor_name="hw-radar-other"
    )
    rows: list[object] = list(fixture["datasetItems"])
    result = classify_run(
        "SUCCEEDED", fixture["output"], len(rows), len(rows), admitted=other_actor
    )

    assert result == RunClassification(C.FAILED, "scope_mismatch", None)


# ── Remaining partial-failure and failure rows ────────────────────────────────


def test_failed_or_aborted_without_items_is_failed() -> None:
    fixture = _fixture("failed-with-items")
    admitted = _admitted(fixture)
    output = copy.deepcopy(fixture["output"])
    output["completeness"]["itemsEmitted"] = 0

    for status in ("FAILED", "ABORTED"):
        result = classify_run(status, output, 0, 0, admitted=admitted)
        assert result.completeness is C.FAILED
        assert result.reason == f"remote_failed_empty: {status}"


def test_some_unusable_rows_are_a_partial_failure() -> None:
    fixture = _fixture("complete")
    rows: list[object] = list(fixture["datasetItems"])
    rows[0] = {**fixture["datasetItems"][0], "price": "free"}

    result = classify_run(
        "SUCCEEDED",
        fixture["output"],
        len(rows),
        len(usable_rows(rows)),
        admitted=_admitted(fixture),
    )

    assert result == RunClassification(C.PARTIAL_FAILURE, "unusable_items: 1 of 3", None)


def test_incomplete_report_without_a_cause_is_failed() -> None:
    result = _classify(_fixture("complete"), output=_with_report("complete", complete=False))

    assert result == RunClassification(C.FAILED, "unexplained_incomplete", None)


@pytest.mark.parametrize("status", ["READY", "RUNNING", "TIMING-OUT", "ABORTING", "succeeded"])
def test_non_terminal_status_is_a_caller_error(status: str) -> None:
    with pytest.raises(ValueError, match="non-terminal"):
        _classify(_fixture("complete"), remote_status=status)


def test_impossible_usable_count_is_a_caller_error() -> None:
    fixture = _fixture("complete")

    with pytest.raises(ValueError, match="usable_count"):
        classify_run("SUCCEEDED", fixture["output"], 1, 2, admitted=_admitted(fixture))
